### PR TITLE
added new randomat icon

### PR DESCRIPTION
**Pull request by Histalek**
just added my take on a randomat icon, so maybe someone with PS can apply the dropshadow.

Bomb-Image from pngkey.com 
Dices cropped from the randomdamage icon

### CODE REVIEW

**Comment by TimGoll** [comment]
yeah no problem, I'll do it quick

**Comment by TimGoll** [comment]
your icon style is different to the general TTT item icon style. Is this intended? And why?

**Comment by Histalek** [comment]
is it? then i fucked up i guess

**Comment by TimGoll** [comment]
okay :D no problem^^

**Pull request merged**
